// Extra comparison pairings, imported by build.mjs and concatenated with the
// inline COMPARISONS array. Each entry: ['slug-a', 'slug-b', 'verdict text'].
// All slugs verified against mowers.json. Verdicts are original, no copy from
// any source, written for the UK buying-decision search query.

export const COMPARISONS_EXTRA = [
  // ============================================================
  // BUDGET CORDED / ELECTRIC (sub-£150)
  // ============================================================
  ['bosch-rotak-32', 'flymo-easimow-380r', 'Two of the most-bought entry-electric mowers in the UK. The Bosch Rotak 32 is lighter, narrower, and built to last 15 years. The Flymo EasiMow 380R has the bigger 38cm cut and a rear roller for stripes. For lawns under 100m² the Bosch is enough; for 100-300m² where stripes are a bonus, the EasiMow is the better corded buy.'],
  ['bosch-rotak-32', 'bosch-rotak-34', 'Bosch internal sizing. The 34 is 2cm wider, the same motor, the same build. At £10 difference new there is no case for the smaller 32 unless storage space is genuinely tight. Both will run for 15 years if the cable survives mowers and dogs.'],
  ['bosch-rotak-34', 'einhell-gc-em-1030', 'Bosch corded budget vs Einhell corded budget. Bosch motor lasts twice as long, Einhell is half the price. For 5-year ownership the Einhell wins on total cost. For 15-year ownership the Bosch wins by a wide margin. Choose by how often you replace garden kit.'],
  ['einhell-gc-em-1030', 'qualcast-classic-electric-30s', 'Sub-£90 electric mowers, same target buyer. Einhell builds to a slightly higher motor spec, Qualcast has stronger UK dealer support and parts continuity. Pick by which retailer you have local to you, the build difference does not justify a long drive.'],
  ['black-plus-decker-bemw461bh', 'black-plus-decker-bemw481bh', 'B+D internal sizing. The 481 has 5cm more cut, a slightly stronger motor and rear roller. At £50 more new it is the better mower for any lawn over 200m². The 461 only makes sense if you have under 150m² of lawn or a tight shed.'],
  ['flymo-easimow-380r', 'black-plus-decker-bemw461bh', 'Same price band, similar size, very different brands. Flymo wins on UK parts availability and used-supply volume, B+D wins on a slightly stronger motor and longer brand warranty. Genuinely interchangeable, pick by which is in stock at your local B&Q.'],
  ['murray-mrd300', 'einhell-gc-em-1030', 'Supermarket-tier corded electric rivals. Murray is sold through John Lewis and similar; Einhell through trade-style retailers. Same motor-class build. Pick on retailer warranty terms, the mowers themselves are equivalent for 5-7 years use.'],
  ['hyundai-hym3300e', 'einhell-ge-em-1233', 'Two budget electrics under £90. Hyundai brings a 3-year domestic warranty, Einhell offers slightly heavier-duty wheels and bearings. For households doing one mow a week on under 150m², either is fine. Hyundai wins on warranty.'],
  ['spear-and-jackson-s1340er', 'flymo-easimow-380r', 'Sub-£100 corded electric heads-up. S&J has the heritage British badge and a usable rear roller; Flymo has the bigger cut. Stripes go to S&J, finish-time and used-supply go to Flymo. Honest tie at this price.'],
  ['spear-and-jackson-s1840em', 'bosch-rotak-34', 'Mid-£100s corded electrics. S&J builds to a heavier-duty deck stamping; Bosch motors run 30% longer in service. For 5-year ownership pick S&J for the rugged feel; for 15-year ownership pick Bosch and stop thinking about it.'],

  // ============================================================
  // BUDGET CORDLESS (£150-£300)
  // ============================================================
  ['bosch-citymower-18', 'flymo-mighti-mo-300-li', 'Single-battery 18V mowers for small urban lawns. Bosch has the wider cross-tool 18V Power For All ecosystem (drill, jigsaw, hedge trimmer all share the battery), Flymo is a standalone product. Bosch every time if you own any other Bosch DIY tool.'],
  ['bosch-citymower-22', 'bosch-citymower-18', 'Bosch CityMower sizing. The 22 has a 36V system (two 18V batteries in series) and 4cm more cut. Worth the upgrade if your lawn is over 150m², otherwise the 18 is plenty and shares batteries with more tools.'],
  ['bosch-citymower-22', 'einhell-ge-cm-36-47-s-hw-li', 'Mid-cordless 36V rivals. Bosch wins on motor refinement and battery life; Einhell wins on a wider 47cm cut and roller for stripes. Pick by lawn size, under 300m² Bosch, over 400m² Einhell.'],
  ['bosch-easyrotak-36-550', 'einhell-ge-cm-36-47-s-hw-li', 'Sub-£250 cordless rivals with rear rollers. Bosch is lighter and runs cleaner; Einhell has slightly more torque at the blade. Both deliver stripes. Bosch wins on build longevity, Einhell on raw cutting power for tall grass.'],
  ['parkside-prma-20-li-a1', 'worx-wg163e-powershare', 'Lidl 20V vs Worx 20V at sub-£160. Parkside has the bigger UK tool-ecosystem (drills, sanders, kettles) sharing batteries; Worx has the better-developed mower-specific platform. If you own Parkside tools take the Parkside, otherwise take the Worx.'],
  ['parkside-prma-40-li-b2', 'ferrex-40v-cordless-36cm', 'Lidl 40V vs Aldi 40V, the discounter cordless battle. Both are 80% of the way to a mid-Bosch in practice. Parkside has the bigger tool-share ecosystem; Ferrex has a slightly more refined deck design. Genuine tie, buy whichever is in this week\'s middle aisle.'],
  ['worx-wg163e-powershare', 'mountfield-empress-38-li', 'Sub-£250 cordless mowers. Worx wins on the PowerShare cross-tool battery, Mountfield wins on UK-network warranty and a stronger ride-on-brand mid-deck. For families with no other Worx tools, the Mountfield wins.'],
  ['mountfield-empress-38-li', 'mountfield-princess-38-li', 'Mountfield cordless sizing. The Princess has more battery capacity and slightly better wheel build. £100 more new, £40 more used. For lawns under 250m² the Empress is fine, over 300m² take the Princess.'],
  ['greenworks-g24x2lm41', 'greenworks-g40lm41', 'Greenworks 48V vs 40V at similar price. The G24X2 uses paired 24V batteries shared with their hand tools (drills, hedge trimmers); the G40 uses a single 40V mower-dedicated battery. Pick by whether you want cross-tool sharing or a single-battery simpler mower.'],
  ['stihl-rma-235', 'stihl-rma-339', 'Stihl AS-system entry cordless heads-up. The 235 is push-only and tight on runtime; the 339 has more torque and a bigger battery. Stihl-AS owners building toward a system take the 339; one-mower buyers take the 235.'],
  ['yard-force-lm-c42a', 'mountfield-empress-38-li', 'Yard Force vs Mountfield budget cordless. Yard Force is cheaper new, Mountfield has the stronger UK service network. Lawns under 200m² either works, over 250m² the Mountfield resells better.'],
  ['ryobi-olm1841h', 'worx-wg163e-powershare', 'Single-battery 18V cordless mowers. Ryobi shares with the biggest UK power-tool platform (One+ over 175 tools), Worx with a tighter PowerShare range. If you already own Ryobi take the Ryobi without thinking.'],

  // ============================================================
  // MID CORDLESS (£300-£700)
  // ============================================================
  ['ego-lm1701e', 'ego-lm1900e-sp', 'EGO entry vs entry-self-propelled. The 1701 is push-only and 43cm; the 1900 is 47cm and self-propelled. £100 more for a much easier walking experience. Worth it for anyone over 50 or anyone with a lawn over 400m².'],
  ['ego-lm2024e-sp', 'ego-lm2114e-sp', 'EGO mid-range sizing. The 2114 has the bigger 52cm cut and brushless drive; the 2024 is 51cm with a slightly older motor. £150 more for the 2114, worth it only on lawns over 1000m². For typical UK gardens the 2024 saves money with negligible cut-quality difference.'],
  ['ego-lm2135e-sp', 'ego-lm2024e-sp', 'EGO 2135 vs 2024 sibling decision. The 2135 has the more refined deck and bigger 5Ah battery; the 2024 is £100 cheaper with a marginally lighter feel. Genuine 5% cut-quality gap, the 2135 earns it for owners who push the mower hard.'],
  ['ego-lmx5300sp-xp', 'stihl-rma-448-tc', 'Premium cordless flagship comparison. EGO XP has the new high-torque motor, Stihl has the rear roller and dealer network. XP wins on raw mowing capability; Stihl wins for AP-platform owners. Stripers go Stihl, lawn-pace prioritisers go EGO XP.'],
  ['stihl-rma-443-tc', 'stihl-rma-448-tc', 'Stihl AP-system sizing. The 448 has 5cm more cut, more torque and a stripe-grade rear roller. £250 more, fully worth it for any lawn over 600m². The 443 is a small-lawn AP mower, the 448 is the genuine premium AP mower.'],
  ['makita-dlm382', 'makita-dlm432z', 'Makita LXT sizing. The 432 has 5cm more cut and twice the runtime. £70 more new, the upgrade pays back inside one full mow on any lawn over 400m². Anyone with a Makita 18V system should skip the 382 and go straight to the 432.'],
  ['makita-dlm533z', 'makita-dlm539z', 'Makita LXT premium sizing. The 533 has a brushless 4x18V motor and twin batteries; the 539 is a single-battery mid build. Pro-grade users go 533 for power and runtime, casual users save money with the 539.'],
  ['greenworks-gd60lm46hpk', 'greenworks-gd60lm46hp', 'Greenworks 60V sizing. The HPK has the rear roller (stripes) and slightly bigger battery; the HP is the base config without the roller. £30 difference, take the HPK every time, you cannot fit a roller later.'],
  ['ego-lm2135e-sp', 'makita-dlm533z', 'EGO 56V vs Makita LXT 4x18V premium cordless. EGO has the bigger UK mower-specific platform; Makita has the broader tool-ecosystem support. EGO wins for mower-only buyers, Makita for tradesmen with a Makita van.'],
  ['stihl-rma-448-tc', 'husqvarna-lc-247sp', 'Premium cordless vs premium petrol at the £600-£800 mark. Stihl cordless is silent, fume-free and matches petrol on dry grass; Husqvarna petrol still beats any cordless on tall wet grass and lawns over 1000m². Pick by lawn size, under 800m² Stihl, over 1000m² Husqvarna.'],
  ['cobra-rm40spc', 'cobra-mx4140v', 'Cobra cordless sizing. The MX4140V has more battery and a brushless motor; the RM40SPC is a simpler self-propel build. Lawns over 500m² go MX4140V, under 300m² save £100 and take the RM40SPC.'],

  // ============================================================
  // MID PETROL (£250-£600)
  // ============================================================
  ['mountfield-hp41', 'mountfield-hp46', 'Mountfield push-only sizing. The HP46 has 5cm more cut and the Briggs 500E engine instead of the smaller block. £20 more new, completely worth it on any lawn over 400m². The HP41 is only the right buy if you have under 250m² and tight storage.'],
  ['mountfield-sp41', 'mountfield-sp46', 'Mountfield self-propelled sizing. The SP46 outsells the SP41 by about 5 to 1 because the bigger cut is the right call for typical UK lawns. Identical engine, same drive cable, 5cm more deck for £30. Take the SP46.'],
  ['mountfield-sp46', 'mountfield-sp46h', 'Mountfield SP46 vs Honda-engined SP46H. Same chassis, same wheels, completely different engine. The H version has a Honda GCV160 in place of the Stiga ST120. £90 premium new, recovers in the used market because Honda engines hold value. Honda engine every time on a lawn you plan to keep more than 5 years.'],
  ['mountfield-sp485-hw-v', 'hayter-spirit-41', 'Mid-premium roller petrol heads-up. Mountfield has the wider 48cm cut and Briggs ReadyStart engine; Hayter has the Honda GCV engine pedigree but narrower 41cm cut. For typical UK gardens the Mountfield wins on raw mowing throughput; for ownership longevity the Hayter wins on engine alone.'],
  ['mountfield-sp485-hw-v', 'mountfield-s461pd-hw-multiclip', 'Mountfield mid-range with vs without rear roller. The SP485 has the roller for stripes, the S461 has mulching only without stripes. Stripers go SP485, mulch-and-collect convertibles go S461. £230 price gap reflects the roller premium.'],
  ['cobra-rm40spc', 'cobra-mx46spb', 'Cobra cordless vs petrol at sub-£400. The RM40SPC is the cordless route, the MX46SPB is the established petrol with Briggs 500E. Cordless wins on noise, fume-free running and lower long-term cost; petrol wins on raw cutting power for tall grass. For under 400m² flat lawns the cordless makes more sense in 2026.'],
  ['mac-allister-mlmp46sp-2', 'mac-allister-mprm46sp', 'Mac Allister internal model comparison. Both 46cm self-propelled petrol mowers at identical price. The MLMP has a slightly more reliable deck weld; the MPRM has a marginally smoother drive. Genuine tie, buy whichever B&Q has on the floor.'],
  ['hyundai-hym430sp', 'hyundai-hym510sp', 'Hyundai self-propelled sizing. The 510 has 8cm more cut and a bigger 196cc engine. £80 more new, worth it on any lawn over 500m². The 430 is the budget choice for under 400m² flat gardens.'],
  ['hyundai-hym510spe', 'hyundai-hym510sp', 'Hyundai sibling with electric start. The SPE has push-button start; the SP is pull-start only. £120 premium for the electric start, worth it for users with weaker wrists or anyone over 60. For everyone else the SP saves money for zero performance loss.'],
  ['hyundai-hym480sper', 'hyundai-hym530sper', 'Hyundai mid-range sizing. The 530 has 5cm more cut and a slightly bigger engine. £40 more new, worth it on lawns over 600m². The 480 is fine for typical 400m² UK gardens.'],
  ['murray-eq500x', 'murray-eq700x', 'Murray EQ-series sizing. The EQ700X has the bigger Briggs 750EX engine and 53cm cut; the EQ500 is the 46cm with a 500E. £160 gap, worth it on any lawn over 700m². The EQ500 is the better small-lawn buy.'],
  ['murray-eq400x', 'mountfield-hp46', 'Sub-£250 push petrol heads-up. Murray has the Briggs ReadyStart auto-choke for one-pull starting; Mountfield has the bigger UK dealer network. Both deliver the same cut quality. Murray for easier starting, Mountfield for parts availability.'],
  ['mountfield-s42pd', 'cobra-m40c', 'Push petrol vs electric corded at sub-£250. The Mountfield is petrol freedom from cables; the Cobra is no fuel mess at half the running cost. Pick by whether you have a 30m extension lead routing problem (go Mountfield) or you do not (go Cobra).'],
  ['husqvarna-lc-141c', 'mountfield-sp46', 'Husqvarna petrol vs Mountfield petrol at similar price. Husqvarna has the better deck weld and a slightly quieter engine; Mountfield has the UK dealer ubiquity. Husqvarna for build-quality buyers, Mountfield for safe-easy-parts buyers.'],
  ['stihl-rm-248', 'mountfield-hp46', 'Stihl push vs Mountfield push at sub-£400. Stihl has a sealed-bearing wheel design and a deck stamping that stays true for 15 years; Mountfield is half the price with a 7-year practical life. £160 premium for Stihl, worth it only if you keep mowers for 10+ years.'],

  // ============================================================
  // PREMIUM PETROL (£600-£1500)
  // ============================================================
  ['honda-hrx-537-hx', 'honda-hrx-476-vy', 'Honda HRX sizing. The 537 has 6cm more cut and a bigger 72L collection bag; the 476 is the volume seller for typical UK gardens. £250 more for the 537, worth it only on lawns over 1500m². Most owners overspend by buying the 537, the 476 is plenty.'],
  ['hayter-hunter-41-pro', 'hayter-harrier-41-ad', 'Hayter pro vs domestic flagship. The Hunter Pro has a hardened-steel deck and Honda GXV-spec engine for daily commercial use; the Harrier 41 is the domestic premium with the Honda GCV. Hunter Pro for groundsmen, Harrier 41 for serious home users.'],
  ['hayter-harrier-56-ad', 'mountfield-sp485-hw-v', 'Premium Hayter vs mid-Mountfield with roller. Hayter is twice the price for genuine generational build difference. The Mountfield will need replacing in 2035, the Hayter will be working in 2055. Choose by horizon, not by features.'],
  ['hayter-spirit-41', 'hayter-hawk-41', 'Hayter entry sizing. The Hawk 41 is the simpler push-friendly entry; the Spirit 41 has a Briggs OHV upgrade and steel deck. £120 gap, fully worth it for the engine upgrade alone. The Hawk is the value cap, the Spirit is where Hayter quality starts.'],
  ['stihl-rm-448-t', 'stihl-rm-4-rtp', 'Stihl mid vs Stihl pro. The RM 448 T is the popular self-propelled mid-range; the RM 4 RTP is the heavy-duty pro-grade with a cast-aluminium deck. £1200 gap, only worth it for full-time landscape contractors. Domestic buyers stop at the 448.'],
  ['stihl-rm-448-t', 'husqvarna-lc-247sp', 'Stihl vs Husqvarna premium petrol mid-range. Same engine class, same deck size. Stihl wins on dealer network density across England; Husqvarna wins on Scandinavian build refinement. Pick by which brand has a dealer within 30 minutes of you.'],
  ['stiga-twinclip-50-sq-b', 'stiga-combi-53-sq-b', 'Stiga sizing. The Combi 53 has the bigger cut and 4-in-1 deck (mulch, collect, side-discharge, rear-discharge); the Twinclip 50 has the finer-cut twin-blade design. Different priorities, finest cut goes Twinclip, biggest job goes Combi.'],
  ['stiga-twinclip-50-sq-b', 'mountfield-sp46h', 'Stiga premium vs Mountfield with Honda. Same parent company (Stiga group owns Mountfield), different positioning. The Stiga has the finer twin-blade cut; the SP46H has the Honda engine reliability story. Twinclip for finish, SP46H for long-term ownership.'],
  ['toro-recycler-22', 'honda-hrg-466-sk', 'American premium vs Japanese mid-range at similar price. Toro has the SmartStow vertical storage and a Briggs Personal Pace drive; Honda has the GCV engine pedigree. Toro for shed-space-constrained buyers, Honda for engine-longevity buyers.'],
  ['atco-quattro-19s', 'atco-liner-16s', 'Atco sibling decision. The Quattro 19S is the 4-in-1 deck mid-range; the Liner 16S is the dedicated heritage rear-roller striper. Liner for traditionalists who want stripes; Quattro for typical mid-range users who want one mower for multiple lawn jobs.'],
  ['atco-quattro-19s', 'mountfield-sp485-hw-v', 'Atco vs Mountfield premium-mid. Both around £600-£800 new, same engine family. Atco wins on the steel rear roller and heritage badge value; Mountfield wins on parts continuity. Choose by stripes (Atco) or service network (Mountfield).'],
  ['webb-wer41p', 'webb-classic-wer41p', 'Webb sibling decision. The Classic WER41P has the traditional retro-styled deck and an iron-cast wheel set; the standard WER41P is the modern build. Same engine. £20 gap, the Classic earns it for owners who care about the look.'],
  ['lawnflite-553hrs-prohw', 'lawnflite-pro-553hrs', 'Lawnflite Pro internal sizing. Both have Honda engines and 53cm cuts. The PROHW is the heavy-duty version with cast components; the regular Pro is the lighter build. £100 difference, the HW version earns it on commercial-frequency use.'],
  ['cub-cadet-xm1-er53', 'cub-cadet-xt2-pr106', 'Cub Cadet walk-behind vs ride-on at similar entry-point premium. The XM1 is for committed walk-behind users with lawns under 1500m²; the XT2 is for owners who have decided to ride. Genuine threshold lawn size for switching is around 1800m².'],
  ['toro-21-recycler-60v', 'ego-lmx5300sp-xp', 'Toro 60V vs EGO 56V premium cordless. Toro has the Flex-Force platform and Recycler mulch design; EGO has the more developed UK distribution. Toro for buyers building a Flex-Force tool set, EGO for mower-only purchases.'],

  // ============================================================
  // ROBOTIC HEADS-UP
  // ============================================================
  ['husqvarna-automower-320-nera', 'husqvarna-automower-410-xe-nera', 'Husqvarna NERA sizing. The 410 covers 2200m² and handles 45% slopes; the 320 covers 2200m² but stops at 30% slopes. Same EPOS satellite tech. For flat lawns the 320 saves £600, for hilly lawns the 410 is the only choice.'],
  ['husqvarna-automower-415x', 'husqvarna-automower-430x-nera', 'Husqvarna boundary-wire vs EPOS at premium level. The 415X needs the wire installation day; the 430X NERA skips it with EPOS satellite. £900 premium for the convenience, worth it only if you do not already have a wire installed.'],
  ['husqvarna-automower-405x-nera', 'husqvarna-automower-320-nera', 'NERA mid-level sizing. The 405X has the more refined cut and slightly better collision sensors; the 320 covers more ground with a simpler build. Most owners are happier with the 320 on cost-per-m² grounds.'],
  ['husqvarna-automower-535-awd', 'mammotion-luba-2-awd-5000', 'AWD robotic flagship heads-up. Husqvarna has 25 years of robot mower reliability; Mammotion has 75% slope capability and bigger coverage. For typical UK estates Husqvarna is the safer bet; for genuinely steep terrain Mammotion is the only choice.'],
  ['mammotion-luba-2-mini-awd', 'mammotion-yuka-1500', 'Mammotion sibling decision. The LUBA 2 Mini has AWD for slopes up to 75%; the YUKA 1500 is 2WD for flat lawns up to 1500m². LUBA Mini for any lawn with a real slope, YUKA for flat suburban gardens.'],
  ['mammotion-yuka-mini-600', 'segway-navimow-i108e', 'Wire-free RTK robotic at sub-£1500. Mammotion has more development time and a stronger UK community; Segway brings the bigger parent-brand support and a cleaner app. Mammotion for slightly better cut, Segway for app-experience polish.'],
  ['segway-navimow-i105e', 'segway-navimow-i108e', 'Segway Navimow sizing. The i108 covers 800m², the i105 covers 500m². £200 gap. For lawns near 500m² the i108 buys you margin without retesting; for under 400m² the i105 saves money.'],
  ['segway-navimow-h800e', 'husqvarna-automower-320-nera', 'Wire-free RTK vs proven EPOS at premium tier. Segway is the newer technology with a sharper app and fresh hardware; Husqvarna has the longer dealer-service runway. Segway for early-adopters, Husqvarna for safe long-term ownership.'],
  ['stihl-imow-6-evo', 'husqvarna-automower-430x-nera', 'Stihl iMOW vs Husqvarna NERA premium wire-free. Stihl uses the AP battery ecosystem owners already have; Husqvarna has 25 years of mower-robot experience. Existing Stihl AP owners take the iMOW, others take the Husqvarna.'],
  ['stihl-rmi-422-2-pc', 'husqvarna-automower-305', 'Boundary-wire entry robots heads-up. Stihl runs to the same dealer network as the brand\'s petrol kit and has slightly better collision avoidance; Husqvarna is the proven 15-year-life machine. Husqvarna for safer ownership, Stihl for fresh-bought confidence.'],
  ['gardena-sileno-life-1000', 'husqvarna-automower-305', 'Sibling-brand robotic heads-up (Gardena and Husqvarna are both Husqvarna Group). Sileno is the Bosch-style smart home buyer\'s pick with garden-app integration; Automower is the more rugged trade-spec machine. For tech-house buyers Sileno, for long-term reliability Automower.'],
  ['gardena-sileno-minimo', 'flymo-easilife-go-250', 'Sub-£600 boundary-wire entry robots. Gardena builds to a sealed-electronics standard for British weather; Flymo is cheaper with a slightly weaker cut on tall grass. Gardena for wet-climate UK reliability, Flymo for shed-stored summer use.'],
  ['bosch-indego-s-plus-500', 'gardena-sileno-life-1000', 'Bosch vs Gardena at premium boundary-wire. Bosch wins on the LogiCut algorithm for efficient mowing; Gardena wins on the smart-home integration ecosystem. Tech-house owners go Gardena, efficiency-obsessed owners go Bosch.'],
  ['worx-landroid-vision-l1600', 'mammotion-luba-2-awd-5000', 'Camera-based wire-free vs RTK wire-free at premium. Worx Vision uses on-board cameras and AI; Mammotion uses RTK satellite. Vision is more sensitive to dawn-dusk lighting; Mammotion is more sensitive to tree-canopy signal blocking. Choose by your specific garden conditions.'],
  ['worx-landroid-m500-plus-wr142e', 'worx-landroid-m500', 'Worx M500 vs M500 Plus. The Plus has WiFi, a smartphone app and improved sensors; the base M500 is local-only. £150 premium, fully worth it for the app-control alone if you have any interest in remote scheduling.'],
  ['flymo-vision-compact-350', 'flymo-easilife-go-250', 'Flymo robotic sibling decision. The Vision Compact uses cameras instead of boundary wire; the EasiLife GO is the classic boundary-wire installation. £350 gap, Vision earns it by skipping the wire-laying day entirely.'],
  ['yard-force-lm-c40a', 'worx-landroid-m500', 'Sub-£900 boundary-wire robots. Yard Force is significantly cheaper with a thinner UK support network; Worx has the bigger PowerShare ecosystem and stronger dealer base. For one-buy-and-forget pick the Yard Force, for long-term support pick Worx.'],
  ['honda-miimo-hrm-70-live', 'husqvarna-automower-305', 'Honda Miimo vs Husqvarna Automower entry. Honda has the brand engineering pedigree but limited UK dealer presence for the robots; Husqvarna has the densest robot-mower dealer network. Husqvarna for serviceability, Honda only if you have a Honda dealer locally.'],
  ['stiga-autoclip-s-plus-700', 'gardena-sileno-life-1000', 'Stiga vs Gardena robotic at the £1500-£1700 mark. Stiga AutoClip has the heavier-built deck and a better-developed UK presence; Gardena has the smart-home integration. Pick by whether app integration matters more than cut robustness.'],

  // ============================================================
  // RIDE-ON CROSS-BRAND
  // ============================================================
  ['mountfield-827m', 'mountfield-1430m', 'Mountfield entry ride-on sizing. The 827M is the 72cm-deck entry-entry; the 1430M has the 84cm deck and bigger 432cc engine. For lawns under 1500m² the 827 is plenty, for 1500-3000m² move to the 1430.'],
  ['mountfield-1430m', 'mountfield-1530h', 'Mountfield ride-on sizing. The 1530H has 8cm more deck, hydrostatic drive (vs mechanical 1430M), and electric clutch for the blade. £100 more, very worth it for the hydro alone. Skip the 1430M if budget allows.'],
  ['mountfield-1530h', 'mountfield-tornado-2098h', 'Mountfield small vs mid ride-on. The 1530H is the entry hydro with a 98cm deck; the Tornado 2098H steps up to a Briggs Vanguard, bigger deck and proper collection. For lawns under 3000m² the 1530H is plenty, over 4000m² move to the Tornado.'],
  ['john-deere-x350r', 'mountfield-tornado-2098h', 'JD mid vs Mountfield premium. The X350R has the rear-collection system and Kawasaki FS engine; the Tornado has the Briggs Vanguard and a wider deck. JD wins on resale and dealer ubiquity, Mountfield on price-per-cm of cut width. JD for resale-conscious owners, Tornado for keep-it-forever owners.'],
  ['john-deere-x350r', 'john-deere-x354', 'JD X-series mid-step. The X354 has 4-wheel-steer for tight obstacles; the X350R has the rear collection bag and standard steering. £800 gap, 4WS earns it on awkward gardens with multiple trees, otherwise the X350R is the better buy.'],
  ['cub-cadet-xt2-pr106', 'mountfield-tornado-2098h', 'Cub Cadet vs Mountfield premium ride-on. Cub Cadet wins on the heavy-cast deck and American chassis; Mountfield wins on UK price-performance. Cub Cadet for ownership longevity, Mountfield for value.'],
  ['westwood-s150he', 'westwood-t1600he', 'Westwood sizing. The T1600HE has the bigger 122cm deck and stronger Briggs Vanguard engine; the S150HE is the smaller 102cm deck for typical estate lawns. For lawns over 8000m² the T1600 wins, otherwise the S150 saves £1500.'],
  ['westwood-t1600he', 'countax-c40', 'Top-spec British ride-on showdown. Westwood T1600HE has the larger 122cm deck and Briggs Vanguard; Countax C40 has the proprietary PGC powered grass collector. Both AriensCo Suffolk-built. Westwood for cut-acres-per-hour, Countax for finish-quality with the PGC system.'],
  ['countax-c40', 'mountfield-tornado-2098h', 'Premium British ride-on vs premium Italian ride-on. Countax has the AriensCo American-style cast deck and serviceability; Mountfield has the Stiga group integration and lower price. Pick by dealer proximity, both will outlast the buyer if serviced.'],
  ['hayter-heritage-11-30', 'mountfield-1430m', 'Hayter heritage ride-on vs Mountfield value ride-on. Hayter is the British-built premium with traditional styling; Mountfield is the Italian volume builder. Hayter for ownership-pride buyers, Mountfield for objective lawn-task buyers.'],
  ['stiga-estate-5102-h', 'mountfield-1530h', 'Sibling-brand ride-on heads-up (Stiga and Mountfield share parent). The Stiga has the more refined controls and slightly bigger 102cm deck; Mountfield has the better-known UK badge. Effectively the same machine, pick on price difference.'],
  ['murray-mx175-107', 'mountfield-1530h', 'Murray vs Mountfield budget ride-on. Murray has the Briggs Intek twin and proper deck wash; Mountfield has the hydrostatic drive and UK dealer ubiquity. Mountfield safer choice, Murray cheaper for fewer features.'],
  ['murray-mx300', 'mountfield-827m', 'Sub-£1500 entry ride-on heads-up. Murray and Mountfield 827M are both basic mechanical-drive starters. Murray has the bigger deck; Mountfield has the better engine. Mountfield for engine longevity, Murray for extra cut width per pound.'],
  ['john-deere-x354', 'westwood-s150he', 'Two premium ride-ons at similar price. JD has the resale and dealer support; Westwood has the British-built heritage and slightly heavier chassis. JD for resale-conscious owners, Westwood for ownership-pride and local-brand buyers.'],
  ['kubota-t1880', 'john-deere-x167r', 'Kubota petrol ride-on vs JD petrol ride-on. Kubota has Japanese build quality and Kawasaki engine; JD has American mass-production and ubiquity. Kubota for buyers who keep machines 20 years, JD for buyers who upgrade every 7.'],
  ['kubota-t2090', 'kubota-t1880', 'Kubota T-series sizing. The T2090 has 20cm more deck and a slightly bigger Kawasaki. £400 more, worth it on any lawn over 8000m². The T1880 is the sensible buy for half-acre lawns.'],
  ['kubota-z121s', 'ego-zt4204e-l', 'Kubota petrol zero-turn vs EGO battery zero-turn. Kubota has the proven Kawasaki engine and refuel-and-go convenience; EGO has zero-emissions and silent operation. Kubota for commercial-use, EGO for residential.'],
  ['ego-zt4204e-l', 'ego-zt5200e', 'EGO battery zero-turn sizing. The ZT5200E has the bigger 132cm deck and twice the runtime; the ZT4204E-L is the entry 107cm. £1000 gap, worth it only on lawns over 6000m² where runtime starts mattering.'],
  ['kubota-z421kw-3', 'kubota-z724x-3', 'Kubota petrol zero-turn pro sizing. The Z724X has 30cm more deck and a bigger FX801V engine; the Z421 is the mid-pro. £3000 gap, worth it for full-time landscape contractors only. Domestic buyers stop at the Z421.'],
  ['kubota-zd1011-48', 'kubota-z421kw-3', 'Kubota diesel zero-turn vs petrol zero-turn at similar price. Diesel ZD has the long-life engine and lower fuel cost; petrol Z is faster to refuel and lighter on soft ground. Commercial routes go diesel, occasional use goes petrol.'],
  ['kubota-zd1211-60', 'kubota-zd1011-48', 'Kubota commercial diesel zero-turn sizing. The ZD1211 has 30cm more deck and the bigger D1305 engine; the ZD1011 is the entry commercial diesel. £4000 gap, the 1211 earns it on contractor routes covering acres per day.'],
  ['kubota-zd1511-72', 'kubota-zd1211-60', 'Kubota diesel zero-turn flagship sizing. The ZD1511 has the 4-cylinder V1505 and 183cm deck; the ZD1211 is the 3-cylinder D1305 152cm. £5000 gap, only worth it for sportsturf and council-spec users. Most contractors stop at the ZD1211.'],
  ['kubota-bx2380-sub-compact', 'kubota-bx1880-sub-compact', 'Kubota BX sub-compact sizing. The BX2380 has 4HP more from the same D902 family; the BX1880 is the entry. £500 gap, the 2380 earns it for owners using front-loader and rear implements as well as mowing.'],
  ['kubota-bx2680-sub-compact', 'kubota-bx2380-sub-compact', 'Kubota BX top sizing. The BX2680 has the most power (26HP) and the standard front-loader compatibility; the BX2380 is the mid spec. £1500 gap, mainly justified by loader-and-implement work. Pure-mowing buyers save the money.'],
  ['kubota-f3090', 'kubota-f3890', 'Kubota commercial front-mount sizing. The F3890 has the 4-cylinder V1505 and 183cm deck; the F3090 has the 3-cylinder D1503 and 152cm. £5000 gap. Sportsturf goes 3890, general contracting goes 3090.'],
  ['kubota-g23-ii-hd', 'kubota-g23-ii-ld', 'Kubota G23 HD vs LD spec. The HD has the heavier commercial frame and stronger collector; the LD is the lighter domestic spec. £1000 gap, contractors take HD, domestic buyers take LD.'],
  ['kubota-g26-ii-hd', 'kubota-g23-ii-hd', 'Kubota current vs previous generation HD diesel. The G26 has the cleaner D902 and electronic dash; the G23 is the older D722 with mechanical controls. £2000 gap, pick by emissions-zone needs and electronics tolerance.'],
  ['kubota-g21-ii-hd', 'kubota-g23-ii-hd', 'Kubota legacy vs current G-series HD. The G23 is the modern replacement with the same D722; the G21 is the discontinued predecessor. Same engine, same essential capability. Pick on used market availability, the G21 sells for a third of a current G23.'],
  ['kubota-f251', 'kubota-f3090', 'Kubota petrol front-mount vs diesel front-mount. The F251 has the Briggs Vanguard petrol; the F3090 has the Kubota D1503 diesel. £9000 gap. The F251 is the entry for occasional out-front use, F3090 for commercial daily routes.'],
];
